"""Initial schema

Revision ID: 4e8ad6a45780
Revises: 
Create Date: 2026-04-18 12:07:05.402608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8ad6a45780'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specification_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'APPROVED', 'PUBLISHED', name='documentstatus'), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('confluence_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specification_documents_title'), 'specification_documents', ['title'], unique=False)
    op.create_table('sync_states',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('last_commit_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_mr_checked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('development_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('jira_issue_key', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', name='taskstatus'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['specification_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('development_tasks')
    op.drop_table('sync_states')
    op.drop_index(op.f('ix_specification_documents_title'), table_name='specification_documents')
    op.drop_table('specification_documents')
    # ### end Alembic commands ###
